import React from 'react'

export const ISAUTH='ISAUTH';
export const ISNOTAUTH='INOTAUTH';
export const LISTPRODUCTS='LISTPRODUCTS';
export const SIGNUP_START='SIGNUP_START';
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS';
export const SIGNUP_FAIL='SIGNUP_FAIL';
export const SIGNIN_STARTED='SIGN_STARTED';
export const SIGNIN_SUCCESS='SIGNIN_SUCCESS';
export const SIGNIN_FAIL='SIGNIN_FAIL';
export const RESETAUTHSTATE='RESETAUTHSTATE';